### ISSUE TITLE
Missing binary for darwin-x86_64

### ISSUE THREAD

**Issue by markosski** [n0-computer/dumbpipe#13]
Install script supports darwin-x86_64 however it seems there is no binary available to download for darwin-x86_64

**Comment by Arqu** [comment]
Right, sorry for that. Need to unblock this:
https://github.com/n0-computer/dumbpipe/blob/main/.github/workflows/release.yml#L69
Will aim to get it in this week.

**Comment by markosski** [comment]
@Arqu thank you!

**Comment by Arqu** [comment]
Should be fixed now.
