### ISSUE TITLE
website CSS

### ISSUE THREAD

**Issue by nichoth** [n0-computer/dumbpipe#22]
The website breaks at 1100 x 577

<img width="1065" alt="image" src="https://github.com/n0-computer/dumbpipe/assets/5776508/92d337c0-f8aa-4f3e-8006-28587b2c9f9f">

I would make a PR, but not sure if the website is open source.

**Comment by dignifiedquire** [comment]
for reference, the sites source is here: https://github.com/n0-computer/dumbpipe.dev
