### ISSUE TITLE
Releases are tarbombs

### ISSUE THREAD

**Issue by link2xt** [n0-computer/dumbpipe#6]
I have downloaded the release tarball and it want to extract to `.`:
```
$ tar tf dumbpipe-v0.1.0-linux-x86_64.tar.gz 
./
./dumbpipe
./README.md
./LICENSE-MIT
./complete/
./LICENSE-APACHE
```

I have expected that it would extract to `dumbpipe-v0.1.0-linux-x86_64`.

**Comment by Arqu** [comment]
ACK, will clean up the release folders.
